let country_list = {
  AED: { name: "United Arab Emirates Dirham", flag: "AE" },
  AFN: { name: "Afghan Afghani", flag: "AF" },
  ALL: { name: "Albanian Lek", flag: "AL" },
  AMD: { name: "Armenian Dram", flag: "AM" },
  ANG: { name: "Netherlands Antillean Guilder", flag: "AN" },
  AOA: { name: "Angolan Kwanza", flag: "AO" },
  ARS: { name: "Argentine Peso", flag: "AR" },
  AUD: { name: "Australian Dollar", flag: "AU" },
  AZN: { name: "Azerbaijani Manat", flag: "AZ" },
  BAM: { name: "Bosnia-Herzegovina Convertible Mark", flag: "BA" },
  BBD: { name: "Barbadian Dollar", flag: "BB" },
  BDT: { name: "Bangladeshi Taka", flag: "BD" },
  BGN: { name: "Bulgarian Lev", flag: "BG" },
  BHD: { name: "Bahraini Dinar", flag: "BH" },
  BIF: { name: "Burundian Franc", flag: "BI" },
  BMD: { name: "Bermudian Dollar", flag: "BM" },
  BND: { name: "Brunei Dollar", flag: "BN" },
  BOB: { name: "Bolivian Boliviano", flag: "BO" },
  BRL: { name: "Brazilian Real", flag: "BR" },
  BSD: { name: "Bahamian Dollar", flag: "BS" },
  CAD: { name: "Canadian Dollar", flag: "CA" },
  CHF: { name: "Swiss Franc", flag: "CH" },
  CLP: { name: "Chilean Peso", flag: "CL" },
  CNY: { name: "Chinese Yuan", flag: "CN" },
  COP: { name: "Colombian Peso", flag: "CO" },
  CRC: { name: "Costa Rican Colón", flag: "CR" },
  CZK: { name: "Czech Koruna", flag: "CZ" },
  DKK: { name: "Danish Krone", flag: "DK" },
  DOP: { name: "Dominican Peso", flag: "DO" },
  DZD: { name: "Algerian Dinar", flag: "DZ" },
  EGP: { name: "Egyptian Pound", flag: "EG" },
  EUR: { name: "Euro", flag: "FR" },
  FJD: { name: "Fijian Dollar", flag: "FJ" },
  GBP: { name: "British Pound Sterling", flag: "GB" },
  GHS: { name: "Ghanaian Cedi", flag: "GH" },
  HKD: { name: "Hong Kong Dollar", flag: "HK" },
  HRK: { name: "Croatian Kuna", flag: "HR" },
  HUF: { name: "Hungarian Forint", flag: "HU" },
  IDR: { name: "Indonesian Rupiah", flag: "ID" },
  ILS: { name: "Israeli New Shekel", flag: "IL" },
  INR: { name: "Indian Rupee", flag: "IN" },
  IQD: { name: "Iraqi Dinar", flag: "IQ" },
  IRR: { name: "Iranian Rial", flag: "IR" },
  ISK: { name: "Icelandic Krona", flag: "IS" },
  JMD: { name: "Jamaican Dollar", flag: "JM" },
  JOD: { name: "Jordanian Dinar", flag: "JO" },
  JPY: { name: "Japanese Yen", flag: "JP" },
  KES: { name: "Kenyan Shilling", flag: "KE" },
  KHR: { name: "Cambodian Riel", flag: "KH" },
  KRW: { name: "South Korean Won", flag: "KR" },
  KWD: { name: "Kuwaiti Dinar", flag: "KW" },
  KZT: { name: "Kazakhstani Tenge", flag: "KZ" },
  LAK: { name: "Lao Kip", flag: "LA" },
  LBP: { name: "Lebanese Pound", flag: "LB" },
  LKR: { name: "Sri Lankan Rupee", flag: "LK" },
  LYD: { name: "Libyan Dinar", flag: "LY" },
  MAD: { name: "Moroccan Dirham", flag: "MA" },
  MDL: { name: "Moldovan Leu", flag: "MD" },
  MGA: { name: "Malagasy Ariary", flag: "MG" },
  MKD: { name: "Macedonian Denar", flag: "MK" },
  MMK: { name: "Myanmar Kyat", flag: "MM" },
  MNT: { name: "Mongolian Tögrög", flag: "MN" },
  MUR: { name: "Mauritian Rupee", flag: "MU" },
  MVR: { name: "Maldivian Rufiyaa", flag: "MV" },
  MXN: { name: "Mexican Peso", flag: "MX" },
  MYR: { name: "Malaysian Ringgit", flag: "MY" },
  NGN: { name: "Nigerian Naira", flag: "NG" },
  NOK: { name: "Norwegian Krone", flag: "NO" },
  NPR: { name: "Nepalese Rupee", flag: "NP" },
  NZD: { name: "New Zealand Dollar", flag: "NZ" },
  OMR: { name: "Omani Rial", flag: "OM" },
  PEN: { name: "Peruvian Sol", flag: "PE" },
  PHP: { name: "Philippine Peso", flag: "PH" },
  PKR: { name: "Pakistani Rupee", flag: "PK" },
  PLN: { name: "Polish Zloty", flag: "PL" },
  QAR: { name: "Qatari Riyal", flag: "QA" },
  RON: { name: "Romanian Leu", flag: "RO" },
  RUB: { name: "Russian Ruble", flag: "RU" },
  SAR: { name: "Saudi Riyal", flag: "SA" },
  SEK: { name: "Swedish Krona", flag: "SE" },
  SGD: { name: "Singapore Dollar", flag: "SG" },
  THB: { name: "Thai Baht", flag: "TH" },
  TJS: { name: "Tajikistani Somoni", flag: "TJ" },
  TND: { name: "Tunisian Dinar", flag: "TN" },
  TRY: { name: "Turkish Lira", flag: "TR" },
  TWD: { name: "Taiwan Dollar", flag: "TW" },
  TZS: { name: "Tanzanian Shilling", flag: "TZ" },
  UAH: { name: "Ukrainian Hryvnia", flag: "UA" },
  UGX: { name: "Ugandan Shilling", flag: "UG" },
  USD: { name: "US Dollar", flag: "US" },
  UYU: { name: "Uruguayan Peso", flag: "UY" },
  UZS: { name: "Uzbekistani Som", flag: "UZ" },
  VND: { name: "Vietnamese Dong", flag: "VN" },
  XCD: { name: "East Caribbean Dollar", flag: "AG" },
  ZAR: { name: "South African Rand", flag: "ZA" },
};
